
/*This file is generated by code generator*/

#include "change_password.h"
#include "mvvm/base/view_model.h"

#ifndef TK_CHANGE_PASSWORD_VIEW_MODEL_H
#define TK_CHANGE_PASSWORD_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class change_password_view_model_t
 *
 * view model of change_password
 *
 */
typedef struct _change_password_view_model_t {
  view_model_t view_model;

  /*model object*/
  change_password_t* achange_password;
} change_password_view_model_t;

/**
 * @method change_password_view_model_create
 * 创建change_password view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* change_password_view_model_create(navigator_request_t* req);

/**
 * @method change_password_view_model_create_with
 * 创建change_password view model对象。
 *
 * @annotation ["constructor"]
 * @param {change_password_t*}  achange_password change_password对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* change_password_view_model_create_with(change_password_t* achange_password);

/**
 * @method change_password_view_model_attach
 * 关联到change_password对象。
 *
 * @param {view_model_t*} view_model view_model对象。
 * @param {change_password_t*} change_password change_password对象。
 *
 * @return {ret_t} 返回RET_OK表示成功，否则表示失败。
 */
ret_t change_password_view_model_attach(view_model_t* vm, change_password_t* achange_password);

END_C_DECLS

#endif /*TK_CHANGE_PASSWORD_VIEW_MODEL_H*/
