
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "mvvm/base/utils.h"
#include "login_view_model.h"

static ret_t login_view_model_set_prop(object_t* obj, const char* name, const value_t* v) {
  login_t* alogin = ((login_view_model_t*)(obj))->alogin;

  if (tk_str_ieq("name", name)) {
     str_set(&(alogin->name), value_str(v));

     return RET_OK;
  } else if (tk_str_ieq("password", name)) {
     str_set(&(alogin->password), value_str(v));

     return RET_OK;
  }
  
  return RET_NOT_FOUND;
}


static ret_t login_view_model_get_prop(object_t* obj, const char* name, value_t* v) {
  login_t* alogin = ((login_view_model_t*)(obj))->alogin;

  if (tk_str_ieq("name", name)) {
     value_set_str(v, alogin->name.str);
     return RET_OK;
  } else if (tk_str_ieq("password", name)) {
     value_set_str(v, alogin->password.str);
     return RET_OK;
  }

  return RET_NOT_FOUND;
}


static bool_t login_view_model_can_exec(object_t* obj, const char* name, const char* args) {
 
  login_view_model_t* vm = (login_view_model_t*)(obj);
  login_t* alogin = vm->alogin;
  if (tk_str_ieq("auth", name)) {
    return login_can_auth(alogin);
  }
  return FALSE;
}

static ret_t login_view_model_exec(object_t* obj, const char* name, const char* args) {
 
  login_view_model_t* vm = (login_view_model_t*)(obj);
  login_t* alogin = vm->alogin;
  if (tk_str_ieq("auth", name)) {
    return login_auth(alogin);
  }
  return RET_NOT_FOUND;
}

static ret_t login_view_model_on_destroy(object_t* obj) {
  login_view_model_t* vm = (login_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  
  login_destroy(vm->alogin);

  return view_model_deinit(VIEW_MODEL(obj));
}

static const object_vtable_t s_login_view_model_vtable = {
  "login_view_model_t",
  "login_view_model_t",
  sizeof(login_view_model_t),
  FALSE,
  login_view_model_on_destroy,
  NULL,
  login_view_model_get_prop,
  login_view_model_set_prop,
  NULL,
  NULL,
  login_view_model_can_exec,
  login_view_model_exec
};

view_model_t* login_view_model_create_with(login_t* alogin) {
  object_t* obj = object_create(&s_login_view_model_vtable);
  view_model_t* vm = view_model_init(VIEW_MODEL(obj));
  login_view_model_t* login_view_model = (login_view_model_t*)(vm);

  return_value_if_fail(vm != NULL, NULL);

  login_view_model->alogin = alogin;
  

  return vm;
}

ret_t login_view_model_attach(view_model_t* vm, login_t* alogin) {
  login_view_model_t* login_view_model = (login_view_model_t*)(vm);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  login_view_model->alogin = alogin;

  return RET_OK;
}

view_model_t* login_view_model_create(navigator_request_t* req) {
  login_t* alogin = login_create();
  return_value_if_fail(alogin != NULL, NULL);

  return login_view_model_create_with(alogin);
}
