
/*This file is generated by code generator*/

#include "product_info.h"
#include "mvvm/base/view_model.h"

#ifndef TK_PRODUCT_INFO_VIEW_MODEL_H
#define TK_PRODUCT_INFO_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class product_info_view_model_t
 *
 * view model of product_info
 *
 */
typedef struct _product_info_view_model_t {
  view_model_t view_model;

  /*model object*/
  product_info_t* aproduct_info;
} product_info_view_model_t;

/**
 * @method product_info_view_model_create
 * 创建product_info view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* product_info_view_model_create(navigator_request_t* req);

/**
 * @method product_info_view_model_create_with
 * 创建product_info view model对象。
 *
 * @annotation ["constructor"]
 * @param {product_info_t*}  aproduct_info product_info对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* product_info_view_model_create_with(product_info_t* aproduct_info);

/**
 * @method product_info_view_model_attach
 * 关联到product_info对象。
 *
 * @param {view_model_t*} view_model view_model对象。
 * @param {product_info_t*} product_info product_info对象。
 *
 * @return {ret_t} 返回RET_OK表示成功，否则表示失败。
 */
ret_t product_info_view_model_attach(view_model_t* vm, product_info_t* aproduct_info);

END_C_DECLS

#endif /*TK_PRODUCT_INFO_VIEW_MODEL_H*/
