
/*This file is generated by code generator*/

#include "time_settings.h"
#include "mvvm/base/view_model.h"

#ifndef TK_TIME_SETTINGS_VIEW_MODEL_H
#define TK_TIME_SETTINGS_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class time_settings_view_model_t
 *
 * view model of time_settings
 *
 */
typedef struct _time_settings_view_model_t {
  view_model_t view_model;

  /*model object*/
  time_settings_t* atime_settings;
} time_settings_view_model_t;

/**
 * @method time_settings_view_model_create
 * 创建time_settings view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* time_settings_view_model_create(navigator_request_t* req);

/**
 * @method time_settings_view_model_create_with
 * 创建time_settings view model对象。
 *
 * @annotation ["constructor"]
 * @param {time_settings_t*}  atime_settings time_settings对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* time_settings_view_model_create_with(time_settings_t* atime_settings);

/**
 * @method time_settings_view_model_attach
 * 关联到time_settings对象。
 *
 * @param {view_model_t*} view_model view_model对象。
 * @param {time_settings_t*} time_settings time_settings对象。
 *
 * @return {ret_t} 返回RET_OK表示成功，否则表示失败。
 */
ret_t time_settings_view_model_attach(view_model_t* vm, time_settings_t* atime_settings);

END_C_DECLS

#endif /*TK_TIME_SETTINGS_VIEW_MODEL_H*/
