
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "mvvm/base/utils.h"
#include "user_view_model.h"

static ret_t user_view_model_set_prop(object_t* obj, const char* name, const value_t* v) {
  user_t* user = ((user_view_model_t*)(obj))->user;

  if (tk_str_eq("name", name)) {
    str_set(&(user->name), value_str(v));

    return RET_OK;
  } else if (tk_str_eq("nick_name", name)) {
    str_set(&(user->nick_name), value_str(v));

    return RET_OK;
  } else if (tk_str_eq("password", name)) {
    str_set(&(user->password), value_str(v));

    return RET_OK;
  } else if (tk_str_eq("registered_time", name)) {
    user->registered_time = value_uint64(v);

    return RET_OK;
  } else if (tk_str_eq("last_login_time", name)) {
    user->last_login_time = value_uint64(v);

    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static ret_t user_view_model_get_prop(object_t* obj, const char* name, value_t* v) {
  user_t* user = ((user_view_model_t*)(obj))->user;

  if (tk_str_eq("name", name)) {
    value_set_str(v, user->name.str);
    return RET_OK;
  } else if (tk_str_eq("nick_name", name)) {
    value_set_str(v, user->nick_name.str);
    return RET_OK;
  } else if (tk_str_eq("password", name)) {
    value_set_str(v, user->password.str);
    return RET_OK;
  } else if (tk_str_eq("registered_time", name)) {
    value_set_uint64(v, user->registered_time);
    return RET_OK;
  } else if (tk_str_eq("last_login_time", name)) {
    value_set_uint64(v, user->last_login_time);
    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static bool_t user_view_model_can_exec(object_t* obj, const char* name, const char* args) {
  return FALSE;
}

static ret_t user_view_model_exec(object_t* obj, const char* name, const char* args) {
  return RET_NOT_FOUND;
}

static ret_t user_view_model_on_destroy(object_t* obj) {
  user_view_model_t* vm = (user_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  user_destroy(vm->user);

  return view_model_deinit(VIEW_MODEL(obj));
}

static const object_vtable_t s_user_view_model_vtable = {.type = "user_view_model_t",
                                                         .desc = "user_view_model_t",
                                                         .size = sizeof(user_view_model_t),
                                                         .exec = user_view_model_exec,
                                                         .can_exec = user_view_model_can_exec,
                                                         .get_prop = user_view_model_get_prop,
                                                         .set_prop = user_view_model_set_prop,
                                                         .on_destroy = user_view_model_on_destroy};

view_model_t* user_view_model_create_with(user_t* user) {
  object_t* obj = object_create(&s_user_view_model_vtable);
  view_model_t* vm = view_model_init(VIEW_MODEL(obj));
  user_view_model_t* user_view_model = (user_view_model_t*)(vm);

  return_value_if_fail(vm != NULL, NULL);

  user_view_model->user = user;

  return vm;
}

ret_t user_view_model_attach(view_model_t* vm, user_t* user) {
  user_view_model_t* user_view_model = (user_view_model_t*)(vm);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  user_view_model->user = user;

  return RET_OK;
}

view_model_t* user_view_model_create(navigator_request_t* req) {
  user_t* user = user_create();
  return_value_if_fail(user != NULL, NULL);

  return user_view_model_create_with(user);
}
