
/*This file is generated by code generator*/

#include "users.h"
#include "user_view_model.h"
#include "mvvm/base/view_model_array.h"

#ifndef TK_USERS_VIEW_MODEL_H
#define TK_USERS_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class users_view_model_t
 *
 * view model of users
 *
 */
typedef struct _users_view_model_t {
  view_model_array_t view_model_array;

  /*model object*/
  users_t* ausers;
  view_model_t* user_view_model;
} users_view_model_t;

/**
 * @method users_view_model_create
 * 创建users view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* users_view_model_create(navigator_request_t* req);

/**
 * @method users_view_model_create_with
 * 创建users view model对象。
 *
 * @annotation ["constructor"]
 * @param {users_t*}  ausers users对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* users_view_model_create_with(users_t* ausers);

END_C_DECLS

#endif /*TK_USERS_VIEW_MODEL_H*/
