
/*This file is generated by code generator*/

#include "user_add.h"
#include "mvvm/base/view_model.h"

#ifndef TK_USER_ADD_VIEW_MODEL_H
#define TK_USER_ADD_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class user_add_view_model_t
 *
 * view model of user_add
 *
 */
typedef struct _user_add_view_model_t {
  view_model_t view_model;

  /*model object*/
  user_add_t* auser_add;
} user_add_view_model_t;

/**
 * @method user_add_view_model_create
 * 创建user_add view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* user_add_view_model_create(navigator_request_t* req);

/**
 * @method user_add_view_model_create_with
 * 创建user_add view model对象。
 *
 * @annotation ["constructor"]
 * @param {user_add_t*}  auser_add user_add对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* user_add_view_model_create_with(user_add_t* auser_add);

/**
 * @method user_add_view_model_attach
 * 关联到user_add对象。
 *
 * @param {view_model_t*} view_model view_model对象。
 * @param {user_add_t*} user_add user_add对象。
 *
 * @return {ret_t} 返回RET_OK表示成功，否则表示失败。
 */
ret_t user_add_view_model_attach(view_model_t* vm, user_add_t* auser_add);

END_C_DECLS

#endif /*TK_USER_ADD_VIEW_MODEL_H*/
